### ISSUE TITLE
Memory exhaustion on big files

### ISSUE THREAD

**Issue by fegu** [GaloisInc/xml#6]
This library is great for smaller files. But when we tried parsing a 150 MB XML file where the data consists of data series for 9 installations we observed the memory consumption going from 100MB to 6.5GB and back six times before it stopped on memory exhaustion (I guess the 7th installation had slightly more data than the six before it). It also took several hours to run (yes, that is right). For this reason we could not use it for our project. I can't contribute the XML file as it contains financially sensitive information for a public company, but I can test changes and report back if anyone has suggestions.

**Comment by glguy** [comment]
This library uses the `String` type which is ridiculously memory inefficient. As a result it will never be appropriate for large files. You'll have to use a different approach in this case, unfortuantely.

**Comment by fegu** [comment]
I improved the library changing to Text for most types and also adding strictness annotations (bangs) on the data types. It now seems to run, will test more next week. If it is an improvement I will issue a pull request.

**Comment by fegu** [comment]
The changes I made moved the API towards something resembling the simpler part of the xml-conduit library on hackage. We instead switched to xml-conduit and now parse the same file in about half a minute. I suggest adding a comment to the readme for the xml package to the effect of "for small files only" to "solve" this issue.
